query getUsers($search: String, $paginIter: Int) {
    getUsers(search: $search, paginIter: $paginIter) {
        id
        name
        surname
        patronymic
        login
        phone
        img
    }
}
