version: '3.8'

services:
    database:
        image: 'postgres:14'
        container_name: storylifebd
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data
    cache:
        image: 'redis:latest'
        ports:
            - 6379:6379
    pgadmin:
        image: 'dpage/pgadmin4:latest'
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@mail.ru
            PGADMIN_DEFAULT_PASSWORD: root
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 5080:80
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - database

volumes:
    postgres:
        driver: local
    pgadmin:
