version: '3.8'

services:
    database:
        image: 'postgres:14'
        container_name: storylifebd
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data
    cache:
        image: 'redis:latest'
        ports:
            - 6379:6379

volumes:
    postgres:
        driver: local
