input RegisterInput {
    login: String!
    phone: String!
    password: String!
}

input LoginInput {
    phone: String!
    password: String!
}

mutation RegisterUser($registerInput: RegisterInput) {
    registerUser(registerInput: $registerInput) {
        success
    }
}

mutation LoginUser($loginInput: LoginInput) {
    loginUser(loginInput: $loginInput) {
        access_token
    }
}

query GetCurrentUser {
    getCurrentUser {
        id
        phone
        login
        created_at
        img
        bg
        is_onlite
        message_notifications {
            id
            messages_id
            chat {
                id
            }
        }
    }
}

query GetCurrentUserChats {
    getCurrentUser {
        chats {
            id
            users {
                id
                img
                is_onlite
                login
                phone
            }
        }
    }
}

query GetUser($userId: String!) {
    getUser(userId: $userId) {
        id
        phone
        login
        created_at
        img
        bg
        is_onlite
    }
}

mutation CreateCall($createCallInput: CreateCallInput!) {
    createCall(createCallInput: $createCallInput)
}

subscription NewCreteCall($userId: String!) {
    newCreteCall(userId: $userId) {
        chatId
        usingVideo
    }
}

mutation AcceptCall($acceptCallInput: AcceptCallInput!) {
    acceptCall(acceptCallInput: $acceptCallInput)
}

subscription NewAcceptCall($userId: String!) {
    newAcceptCall(userId: $userId) {
        acceptCall
        chatId
    }
}

mutation CancelCall($userId: String!) {
    cancelCall(userId: $userId)
}

subscription NewCancelCall($userId: String!) {
    newCancelCall(userId: $userId)
}

subscription NewNotification($userId: String!) {
    newNotification(userId: $userId) {
        id
        messages_id
        chat {
            id
        }
    }
}

mutation SetAvatar($avatar: String!) {
    setAvatar(avatar: $avatar)
}

mutation SetBg($bg: String!) {
    setBg(bg: $bg)
}

subscription NewAvatar($userId: String!) {
    newAvatar(userId: $userId)
}

subscription NewBg($userId: String!) {
    newBg(userId: $userId)
}
