type Comment {
    id: String!
    created_at: String!
    txt: String!
    post: Post!
    user: User!
}

type Like {
    id: String!
    post: Post!
    user: User!
}

type Post {
    id: String!
    title: String!
    created_at: String!
    description: String!
    img: String
    user: User!
    likes: [Like!]!
    comments: [Comment!]!
}

type EditPost {
    id: String!
    title: String!
    img: String
}

input CreatePostInput {
    title: String!
    description: String!
    img: String
}

input CreateCommentInput {
    postId: String!
    txt: String!
}

type Query {
    getUserPosts(userId: String!): [Post!]!
    getPosts: [Post!]!
    getPost(postId: String!): Post
}

type Mutation {
    createPost(createPost: CreatePostInput!): String!
    addLike(postId: String!): String!
    addComment(createCommentInput: CreateCommentInput!): String!
    deletePost(postId: String!): String!
    editPost(postId: String!, editPost: CreatePostInput!): String!
}

type Subscription {
    newPost(userId: String!): Post!
    newLike(postId: String!): Like!
    newComment(postId: String!): Comment!
    newDeletePost(postId: String!): String!
    newEditPost(postId: String!): Post!
}
