type Chat {
    id: String!
    users: [User]!
}

type MessageNotification {
    id: String!
    messages_id: [String!]
    chat: Chat!
}

type User {
    id: String!
    login: String!
    name: String!
    surname: String!
    patronymic: String
    about_me: String
    email: String
    place_work: String
    birthday: String
    phone: String!
    password: String!
    created_at: String!
    is_onlite: Boolean!
    img: String
    bg: String
    chats: [Chat]!
    message_notifications: [MessageNotification]!
}

type ResultEditUser {
    login: String!
    name: String!
    surname: String!
    patronymic: String
    about_me: String
    email: String
    place_work: String
    birthday: String
}

input EditUserInput {
    login: String
    name: String
    surname: String
    patronymic: String
    about_me: String
    email: String
    place_work: String
    birthday: String
}

type Query {
    getCurrentUser: User!
    getUser(userId: String!): User
    getUsers(search: String, paginIter: Int): [User]!
}

type Mutation {
    setAvatar(avatar: String!): String!
    setBg(bg: String!): String!
    setOnlineStatus(online: Boolean!): String!
    editUser(editUser: EditUserInput!): String!
}

type Subscription {
    newAvatar(userId: String!): String!
    newBg(userId: String!): String!
    chanhgeOnlineStatus(userId: String!): Boolean!
    newEditUser(userId: String!): ResultEditUser!
}
