type Chat {
    id: String!
    users: [User]!
}

type MessageNotification {
    id: String!
    messages_id: [String!]
    chat: Chat!
}

type User {
    id: String!
    login: String!
    phone: String!
    password: String!
    created_at: String!
    chats: [Chat]!
    message_notifications: [MessageNotification]!
}

type Query {
    getCurrentUser: User!
    getUser(userId: String!): User
    getUsers: [User]!
}
