mutation CreateRoom($userId: String!) {
    createRoom(userId: $userId) {
        id
        users {
            id
            is_onlite
            login
            phone
        }
    }
}

mutation CreateMessage($messageInput: MessageInput!) {
    createMessage(messageInput: $messageInput)
}

subscription NewMessage($roomId: String!) {
    newMessage(roomId: $roomId) {
        id
        user_id
        text
    }
}

subscription NewCreateRoom($userId: String!) {
    newCreateRoom(userId: $userId) {
        id
        users {
            id
            login
            is_onlite
            phone
        }
    }
}

query GetMessages($roomId: String!) {
    getMessages(roomId: $roomId) {
        id
        user_id
        text
    }
}

mutation DeleteNotification($deleteInputNotification: DeleteInputNotification!) {
    deleteNotification(deleteInputNotification: $deleteInputNotification)
}
